### ISSUE TITLE
Formatter crashes if source contains some unicode characters

### ISSUE THREAD

**Issue by f0i** [dfinity/prettier-plugin-motoko#142]
When a source file contains the per mille sign it seems to some times have problems with the size calculation.

mo-fmt version is 0.9.4

Minimal example file:
```motoko
import Float "mo:base/Float";
module {
          public func formatPercent(val : Float) : Text {
    if (true){
    Float.format(#fix 3, val * 10) # "‰";
    }else "";
  };
  };
```

Which produces the following error:
```
$ mo-fmt src/backend/Stats.mo 
panicked at /rust/deps/dlmalloc-0.2.6/src/dlmalloc.rs:1198:13:
assertion failed: psize <= size + max_overhead

Stack:

Error
    at module.exports.__wbg_new_693216e109162396 (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/wasm/pkg/nodejs/wasm.js:200:17)
    at wasm://wasm/00061082:wasm-function[166]:0x15f78
    at wasm://wasm/00061082:wasm-function[59]:0x11931
    at wasm://wasm/00061082:wasm-function[102]:0x14757
    at wasm://wasm/00061082:wasm-function[99]:0x145b5
    at wasm://wasm/00061082:wasm-function[143]:0x1574c
    at wasm://wasm/00061082:wasm-function[70]:0x12fba
    at module.exports.find_comments (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/wasm/pkg/nodejs/wasm.js:129:14)
    at preprocess (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/lib/parsers/motoko-tt-parse/preprocess.js:54:45)
    at Object.parse (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/lib/parsers/motoko-tt-parse/parse.js:13:37)


RuntimeError: unreachable
    at wasm://wasm/00061082:wasm-function[59]:0x11957
    at wasm://wasm/00061082:wasm-function[102]:0x14757
    at wasm://wasm/00061082:wasm-function[99]:0x145b5
    at wasm://wasm/00061082:wasm-function[143]:0x1574c
    at wasm://wasm/00061082:wasm-function[70]:0x12fba
    at module.exports.find_comments (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/wasm/pkg/nodejs/wasm.js:129:14)
    at preprocess (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/lib/parsers/motoko-tt-parse/preprocess.js:54:45)
    at Object.parse (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier-plugin-motoko/lib/parsers/motoko-tt-parse/parse.js:13:37)
    at Object.parse (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier/index.js:7515:23)
    at coreFormat (/usr/local/share/npm-global/lib/node_modules/mo-fmt/node_modules/prettier/index.js:8829:18)
```

**Comment by rvanasa** [comment]
Thanks! I was able to repro and will look into fixing this.
